In [1]:
import os
import json
import numpy as np

In [2]:
save_folder = "dataset"
name = "dataset"
input_name = os.path.join(save_folder, name + ".json")
output_name = os.path.join(save_folder, name + ".npy")

In [3]:
with open(input_name, 'r') as f:
    data = json.load(f)

In [4]:
data

{'00110001': 363,
 '10111011': 941,
 '01011001': 3,
 '10010011': 2485,
 '00011011': 195,
 '10010001': 5040,
 '00010011': 496,
 '10110011': 2426,
 '01111011': 9,
 '01010001': 25,
 '10011001': 494,
 '00010001': 1022,
 '11110011': 2,
 '10110001': 5104,
 '10011011': 940,
 '00011001': 101,
 '00110011': 182,
 '00111011': 51,
 '10111001': 485,
 '00111001': 35,
 '01011011': 6,
 '01110001': 34,
 '01010011': 16,
 '11010001': 3,
 '01110011': 17,
 '01111001': 1,
 '11010011': 1,
 '11011001': 1,
 '11011011': 1,
 '11110001': 1}

In [5]:
def key_convert(key):
    new_key = ""
    for i in range(0, len(key), 2):
        val = 2 * int(key[i]) + int(key[i+1])
        new_key += str(val)
    return new_key


In [6]:
data_converted = {key_convert(key): val for key, val in data.items()}

In [7]:
data_converted

{'0301': 363,
 '2323': 941,
 '1121': 3,
 '2103': 2485,
 '0123': 195,
 '2101': 5040,
 '0103': 496,
 '2303': 2426,
 '1323': 9,
 '1101': 25,
 '2121': 494,
 '0101': 1022,
 '3303': 2,
 '2301': 5104,
 '2123': 940,
 '0121': 101,
 '0303': 182,
 '0323': 51,
 '2321': 485,
 '0321': 35,
 '1123': 6,
 '1301': 34,
 '1103': 16,
 '3101': 3,
 '1303': 17,
 '1321': 1,
 '3103': 1,
 '3121': 1,
 '3123': 1,
 '3301': 1}

In [8]:
def string_to_array(string):
    ls = []
    for c in string:
        ls.append(int(c))
    return ls

In [9]:
data_array = []

for result, count in data_converted.items():
    result = string_to_array(result)
    for i in range(count):
        data_array.append(result)

In [10]:
data_array

[[0, 3, 0, 1],
 [0, 3, 0, 1],
 [0, 3, 0, 1],
 [0, 3, 0, 1],
 [0, 3, 0, 1],
 [0, 3, 0, 1],
 [0, 3, 0, 1],
 [0, 3, 0, 1],
 [0, 3, 0, 1],
 [0, 3, 0, 1],
 [0, 3, 0, 1],
 [0, 3, 0, 1],
 [0, 3, 0, 1],
 [0, 3, 0, 1],
 [0, 3, 0, 1],
 [0, 3, 0, 1],
 [0, 3, 0, 1],
 [0, 3, 0, 1],
 [0, 3, 0, 1],
 [0, 3, 0, 1],
 [0, 3, 0, 1],
 [0, 3, 0, 1],
 [0, 3, 0, 1],
 [0, 3, 0, 1],
 [0, 3, 0, 1],
 [0, 3, 0, 1],
 [0, 3, 0, 1],
 [0, 3, 0, 1],
 [0, 3, 0, 1],
 [0, 3, 0, 1],
 [0, 3, 0, 1],
 [0, 3, 0, 1],
 [0, 3, 0, 1],
 [0, 3, 0, 1],
 [0, 3, 0, 1],
 [0, 3, 0, 1],
 [0, 3, 0, 1],
 [0, 3, 0, 1],
 [0, 3, 0, 1],
 [0, 3, 0, 1],
 [0, 3, 0, 1],
 [0, 3, 0, 1],
 [0, 3, 0, 1],
 [0, 3, 0, 1],
 [0, 3, 0, 1],
 [0, 3, 0, 1],
 [0, 3, 0, 1],
 [0, 3, 0, 1],
 [0, 3, 0, 1],
 [0, 3, 0, 1],
 [0, 3, 0, 1],
 [0, 3, 0, 1],
 [0, 3, 0, 1],
 [0, 3, 0, 1],
 [0, 3, 0, 1],
 [0, 3, 0, 1],
 [0, 3, 0, 1],
 [0, 3, 0, 1],
 [0, 3, 0, 1],
 [0, 3, 0, 1],
 [0, 3, 0, 1],
 [0, 3, 0, 1],
 [0, 3, 0, 1],
 [0, 3, 0, 1],
 [0, 3, 0, 1],
 [0, 3, 0, 1],
 [0, 3, 0,

In [11]:
data_array = np.array(data_array)

In [12]:
data_array_rescaled = data_array * 1/4 + 1/8

In [13]:
data_array_rescaled

array([[0.125, 0.875, 0.125, 0.375],
       [0.125, 0.875, 0.125, 0.375],
       [0.125, 0.875, 0.125, 0.375],
       ...,
       [0.875, 0.375, 0.625, 0.375],
       [0.875, 0.375, 0.625, 0.875],
       [0.875, 0.875, 0.125, 0.375]])

In [14]:
rng = np.random.default_rng()

In [15]:
data_array_spread = data_array_rescaled + rng.uniform(low = -1/8, high = 1/8, size = data_array_rescaled.shape)

In [16]:
data_array_spread

array([[0.05796809, 0.99221192, 0.18007447, 0.39239969],
       [0.15503255, 0.86606758, 0.05970968, 0.38562336],
       [0.17360797, 0.77943664, 0.22900549, 0.25331014],
       ...,
       [0.93596947, 0.29013512, 0.59159993, 0.3177587 ],
       [0.81328199, 0.3557668 , 0.5496249 , 0.99804192],
       [0.86518901, 0.8201319 , 0.16949653, 0.4613597 ]])

In [17]:
data_array_try_smear = data_array_spread + 0.1 * rng.standard_normal(size = data_array.shape)

In [18]:
data_array_try_smear

array([[0.22623759, 0.89513221, 0.38569896, 0.36755241],
       [0.2104556 , 0.99467451, 0.01770609, 0.46760388],
       [0.13881856, 0.87695348, 0.2597558 , 0.31825066],
       ...,
       [0.93326431, 0.30004156, 0.68643019, 0.16775284],
       [0.57852725, 0.38947711, 0.64027193, 0.96771737],
       [0.96939843, 0.80032157, 0.09973308, 0.38007525]])

In [19]:
data_array_smeared = np.where((data_array_try_smear>=0) & (data_array_try_smear<=1), data_array_try_smear, data_array_spread) 
# make sure the output is between 0 and 1

In [20]:
data_array_smeared

array([[0.22623759, 0.89513221, 0.38569896, 0.36755241],
       [0.2104556 , 0.99467451, 0.01770609, 0.46760388],
       [0.13881856, 0.87695348, 0.2597558 , 0.31825066],
       ...,
       [0.93326431, 0.30004156, 0.68643019, 0.16775284],
       [0.57852725, 0.38947711, 0.64027193, 0.96771737],
       [0.96939843, 0.80032157, 0.09973308, 0.38007525]])

In [21]:
np.save(output_name, data_array_smeared)